name: Scheduled Database Functions

on:
  schedule:
    # Run monthly interest calculation - 1st of every month at 2 AM UTC
    - cron: '0 2 1 * *'
    # Run cleanup of expired tokens - Every day at 3 AM UTC
    - cron: '0 3 * * *'
    # Run transaction totals update - Every Sunday at 1 AM UTC
    - cron: '0 1 * * 0'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

jobs:
  run-scheduled-functions:
    name: Execute Scheduled Database Functions
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary python-dotenv

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Get RDS endpoint
        id: rds
        run: |
          RDS_ENDPOINT=$(aws rds describe-db-instances \
            --db-instance-identifier microbanking-db \
            --query 'DBInstances[0].Endpoint.Address' \
            --output text)
          echo "endpoint=$RDS_ENDPOINT" >> $GITHUB_OUTPUT

      - name: Run scheduled functions
        env:
          DB_HOST: ${{ steps.rds.outputs.endpoint }}
          DB_PORT: 5432
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python scripts/run_scheduled_functions.py

      - name: Send notification
        if: always()
        uses: slackapi/slack-github-action@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "Database Functions Execution Report",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Scheduled Database Functions Executed*\n*Status:* ${{ job.status }}\n*Timestamp:* <!date^${{ github.server_url }}^Posted {date_num} {time_secs}|Posted>"
                  }
                }
              ]
            }

  run-integrity-checks:
    name: Run Database Integrity Checks
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2-binary

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Get RDS endpoint
        id: rds
        run: |
          RDS_ENDPOINT=$(aws rds describe-db-instances \
            --db-instance-identifier microbanking-db \
            --query 'DBInstances[0].Endpoint.Address' \
            --output text)
          echo "endpoint=$RDS_ENDPOINT" >> $GITHUB_OUTPUT

      - name: Run integrity checks
        env:
          DB_HOST: ${{ steps.rds.outputs.endpoint }}
          DB_PORT: 5432
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          python scripts/integrity_check.py
